# Generated by Django 4.1.6 on 2023-07-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=100)),
                ('fieldofstudy', models.CharField(max_length=256)),
                ('institutionname', models.CharField(max_length=256)),
                ('startyear', models.IntegerField(null=True)),
                ('endyear', models.IntegerField(null=True)),
            ],
        ),
    ]
