# Generated by Django 4.1.6 on 2023-07-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
