# Generated by Django 4.1.6 on 2023-07-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=245)),
                ('url', models.URLField(blank=True)),
                ('imageurl', models.ImageField(upload_to='project/')),
                ('summary', models.TextField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
