# Generated by Django 4.1.6 on 2023-07-02 19:55

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('Apps', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologyused',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
