# Generated by Django 4.1.6 on 2023-07-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0010_portfolio_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cv_url',
            field=models.FileField(blank=True, upload_to='Resume/'),
        ),
    ]
