# Generated by Django 4.1.6 on 2023-07-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0011_portfolio_cv_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal1', models.CharField(max_length=254)),
                ('Goal2', models.CharField(max_length=254)),
                ('Goal3', models.CharField(max_length=254)),
                ('Goal4', models.CharField(max_length=254)),
                ('Goal5', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength1', models.CharField(max_length=254)),
                ('strength2', models.CharField(max_length=254)),
                ('strength3', models.CharField(max_length=254)),
                ('strength4', models.CharField(max_length=254)),
                ('strength5', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WhyHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason1', models.CharField(max_length=254)),
                ('reason2', models.CharField(max_length=254)),
                ('reason3', models.CharField(max_length=254)),
                ('reason4', models.CharField(max_length=254)),
                ('reason5', models.CharField(max_length=254)),
            ],
        ),
    ]
