# Generated by Django 4.1.6 on 2023-07-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0012_futuregoals_strength_whyhire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuregoals',
            old_name='Goal1',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='strength',
            old_name='strength1',
            new_name='strength',
        ),
        migrations.RenameField(
            model_name='whyhire',
            old_name='reason1',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='futuregoals',
            name='Goal2',
        ),
        migrations.RemoveField(
            model_name='futuregoals',
            name='Goal3',
        ),
        migrations.RemoveField(
            model_name='futuregoals',
            name='Goal4',
        ),
        migrations.RemoveField(
            model_name='futuregoals',
            name='Goal5',
        ),
        migrations.RemoveField(
            model_name='strength',
            name='strength2',
        ),
        migrations.RemoveField(
            model_name='strength',
            name='strength3',
        ),
        migrations.RemoveField(
            model_name='strength',
            name='strength4',
        ),
        migrations.RemoveField(
            model_name='strength',
            name='strength5',
        ),
        migrations.RemoveField(
            model_name='whyhire',
            name='reason2',
        ),
        migrations.RemoveField(
            model_name='whyhire',
            name='reason3',
        ),
        migrations.RemoveField(
            model_name='whyhire',
            name='reason4',
        ),
        migrations.RemoveField(
            model_name='whyhire',
            name='reason5',
        ),
    ]
